name: sindu_store
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animations: ^2.0.2
  auto_size_text: ^3.0.0
  blue_thermal_printer: ^1.2.0
  cloud_firestore: ^3.1.10
  deep_collection: ^1.0.2
  delayed_display: ^2.0.0
  equatable: ^2.0.3
  firebase_auth: ^3.3.10
  firebase_core: ^1.13.1
  firebase_crashlytics: ^2.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.3
  flutterfire_ui: ^0.4.0+3
  formz: ^0.4.1
  intl: ^0.17.0
  ionicons: ^0.1.2
  json_annotation: ^4.4.0
  json_table: ^2.0.1
  local_auth: ^1.1.11
  modal_bottom_sheet: ^2.0.1
  numeric_keyboard: ^1.1.0
  page_transition: ^2.0.5
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_512.png"

flutter_native_splash:
  color: "#1A2C50"

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: "assets/logo_yellow.png"

  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: MaisonNeue
      fonts:
        - asset: fonts/MaisonNeue-Book.otf
        - asset: fonts/MaisonNeue-Bold.otf
          weight: 700
        - asset: fonts/MaisonNeue-Demi.otf
          weight: 600
        - asset: fonts/MaisonNeue-Medium.otf
          weight: 500
        - asset: fonts/MaisonNeue-Light.otf
          weight: 300
